# Generated by Django 2.2.5 on 2021-03-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_str', models.CharField(max_length=512, verbose_name='input_str')),
                ('type_str', models.CharField(max_length=32, verbose_name='type_str')),
                ('username_str', models.CharField(max_length=128, verbose_name='username_str')),
                ('dt_str', models.CharField(max_length=128, verbose_name='dt_str')),
                ('x_str', models.CharField(max_length=16, verbose_name='x_str')),
                ('y_str', models.CharField(max_length=16, verbose_name='y_str')),
            ],
        ),
    ]
